server:
  port: 8080
spring:
  application:
    name: github-search

github:
  baseUrl: https://api.github.com
  acceptHeader: application/vnd.github.mercy-preview+json

retrofit:
  callTimeoutInSeconds: 15
