server:
  port: 8080
spring:
  application:
    name: github-search

github:
  base-url: https://api.github.com
  accept-header: application/vnd.github.mercy-preview+json

retrofit:
  call-timeout: 15s
