server:
  port: 8080
spring:
  application:
    name: github-search

github:
  base-url: https://api.github.com
  accept-header: application/vnd.github.mercy-preview+json

retrofit:
  call-timeout: 15s

---

spring:
  profiles: test

github:
  base-url: http://127.0.0.1:8000
